---
abstract: 'Safe, Sane, and Simple passphrase salting,'
author:
  - 'David Oswald <davido [@at] cpan [d.o.t] org>'
build_requires:
  English: 0
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.62
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Authen-Passphrase-SaltedSHA512
no_index:
  directory:
    - t
    - inc
requires:
  Authen::Passphrase: 0
  Bytes::Random::Secure: 0.20
  perl: 5.008000
resources: {}
version: 0.07
